### ISSUE TITLE
Explain how to setup an incremental SBT build with sbt-guardrail

### ISSUE THREAD

**Issue by sledorze** [twilio/sbt-guardrail#18]
I'm wondering if I'm doing anything wrong but regeneration is done even of the input file and generated file have not changed.
Maybe that's not the scope of the plugin.. can it be clarified?

**Comment by blast-hardcheese** [comment]
@sledorze There is currently no state preserved between plugin runs. The assumption was that watching file events for generated files would be uncommon, and that the file hashes themselves don't change, so they'd be reused instead of recompiled.

Are you experiencing a different behaviour? I wouldn't mind this functionality changing, I just don't have the time to make the change right now.

**Comment by sledorze** [comment]
I've dived into it and I had a zombie sbt process..
Works as expected! :)

**Comment by blast-hardcheese** [comment]
Spooky!
